site_name: MaLAPA Collaboration

theme:
  name: material
  logo: assets/logo.webp
  favicon: assets/favicon.ico
  palette:
    # Set primary to exactly #3A8ACF?
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.share
    - navigation.search.suggest
    - navigation.search.suggest.index
    - navigation.search.suggest.highlight
    - navigation.search.suggest.share

nav:
  - Home: index.md
  - Resources:
      - Data: resources/data.md
      - Discord: https://discord.gg/qPJx5T36
      - Publications: resources/publications.md
      - Software: resources/software.md
  - Workshops: workshops.md
  - Committee: committee.md
  - Contact Us: contact.md
